# Generated by Django 5.1.4 on 2024-12-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgAdminTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('other', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pg_admin_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PgDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('deskription', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pg_db',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
